# Generated by Django 2.2.4 on 2019-08-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_groupsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupsettings',
            name='warnings',
            field=models.ManyToManyField(related_name='warned_users', to='bot.UserSettings'),
        ),
        migrations.AlterField(
            model_name='groupsettings',
            name='groupname',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
