# Generated by Django 2.2.4 on 2019-08-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20190819_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupsettings',
            name='dev_mode',
            field=models.BooleanField(default=False),
        ),
    ]
