# Generated by Django 2.2.4 on 2019-08-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_warnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupsettings',
            name='rules',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupsettings',
            name='welcome',
            field=models.TextField(blank=True, null=True),
        ),
    ]
